# Generated by Django 4.2.16 on 2024-11-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0003_post_content_post_created_on_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default=''),
        ),
    ]
